### ISSUE TITLE
Model instance builtin fields

### ISSUE THREAD

**Issue by mrastiak** [Carrene/restfulpy-client.js#29]
When creating an instance of restfulpy models we expect that it contains fields from metadata of that model

**Comment by pylover** [comment]
Please update this issue

**Comment by pylover** [comment]
@mrastiak 

Please update us

**Comment by mrastiak** [comment]
@pylover Based on restfulpy-client tests the built-in fields are available but on using models in a project we had a problem with built-in fields and they weren't available.
This issue was pending on changes to model response.
